import type { Metadata } from 'next'
import { Inter, Recursive } from 'next/font/google'
import '@/styles/globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { Toaster } from '@/components/ui/sonner'

const inter = Inter({ subsets: ['latin'] })
const recursive = Recursive({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  authModal
}: Readonly<{
  children: React.ReactNode
  authModal: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={recursive.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {authModal}
          {children}
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  )
}
